spring.application.name=mathgate
spring.datasource.url=jdbc:postgresql://localhost:5432/mathgate
spring.datasource.username=mathgate_user
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
